language: node_js
node_js: 
  - "v8.11.3"
npm:
  - "6.3.0"
cache:
  directories:
    - "node_modules"

services:
  - postgresql

before_script:
  - psql -c "create database stacklite;" -U postgres
  - npm run migrate

after_success:
- npm run coverage