language: node_js
node_js: 
  - "v8.11.3"
npm:
  - "6.3.0"
cache:
  directories:
    - "node_modules"
services:
  - postgresql

addons:
  postgresql: "9.5"
  apt:
      packages:
      - postgresql-9.5
      - postgresql-client-9.5
env:
  global:
  - PGPORT=5432

before_script:
  - psql -c "ALTER USER postgres WITH PASSWORD 'postgres';" -U postgres
  - psql -c "create database stackLite;" -U postgres
  - npm run migrate

after_success:
- npm run coverage