language: node_js
node_js: 
  - "v8.11.3"
npm:
  - "6.3.0"
cache:
  directories:
    - "node_modules"
services:
  - postgresql

sudo: false
dist: trusty
addons:
    postgresql: "9.5"
services:
    - postgresql
env:
  global:
  - PGPORT=5432

before_script:
  - psql -c "create database stackLite;" -U postgres
  - npm run migrate

after_success:
- npm run coverage